---
services:
  simple-codeql-local-scanner:
    container_name: simple-codeql-local-scanner
    image: mcr.microsoft.com/cstsectools/codeql-container:latest
    volumes:
      - /f/node_sandbox/NodeTestBench:/opt/src
      - ./entrypoint.sh:/entrypoint.sh
      - ./codeql-results:/opt/results
    entrypoint: ["bash", "entrypoint.sh"]
